### ISSUE TITLE
Aggiornamento screencast

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-user-guide-docs#13]
Ciao @Valair,
stavo vedendo uno degli screencast (sito_primario) e ho notato due cose che dovrebbero essere sistemate (in tutti i video):
- la larghezza del browser è eccessiva e lo spazio laterale è privo di contenuto (la larghezza schermo potrebbe essere di 1440px)
- è presente la barra in alto con l'avviso "ambiente di sviluppo locale" che invece non dovrebbe apparire

**Comment by pdavide** [comment]
Nel video "sito_primario" allungare di un altro secondo il cartello "dopo aver inserito il codice di tracciamento" e nel testo del cartello mettere:
> Verifica l'attivazione sul portale
> dopo aver inserito il codice di tracciamento
> nel sito istituzionale

**Comment by Valair** [comment]
@pdavide ho caricato una nuova versione dello screencast `sito_primario`; se riesci a darmi un feedback provvedo ad aggiornare anche gli altri

**Comment by pdavide** [comment]
Ok puoi procedere anche gli altri

**Comment by Valair** [comment]
@pdavide screencast aggiornati
