### ISSUE TITLE
Fix video registrazione sito primario

### ISSUE THREAD

**Issue by danielaiozzo** [AgID/wai-user-guide-docs#3]
@Valair Il titolo "inserire lo script di tracciamento Javascript nel sito web registrato" non corrisponde al contenuto dello screencast (che mostra un click sul pulsante di verifica attivazione sito)

**Comment by Valair** [comment]
ciao @danielaiozzo , in realtà quello non è il titolo dello screencast; tutto il video riguarda la "registrazione sito istituzionale", mostrato all'inizio.
Come dicevamo nella call, è stato spezzato in due parti: nella prima l'utente registra il sito istituzionale e si conclude con il click che mostra lo stato inattivo. A questo punto quel messaggio indica che l'utente deve, appunto, inserire lo script di tracciamento nel suo sito web.
Fatto ciò, il video riprende mostrando che il sito diventa "attivo".
Immagino che il fraintendimento sia derivato dall'aver usato lo stesso stile per i due messaggi, magari procedo cambiando riducento la dimensione del testo o cambiando colore di sfondo, che ne pensi?

**Comment by danielaiozzo** [comment]
uhm ok @Valair. Si può aggiungere allora il passaggio che mostra la mail ricevuta che contiene lo script (e subito dopo il click di attivazione..)? 

Il fraintendimento è forse anche derivante dallo stile come dici ...il punto è che se leggo all'inizio "inserire sito istituzionale" e vedo la procedura, poi leggendo "inserire javascript (...)" mi aspetterei quasi di vedere come inserire lo script (ad esempio in che punto della pagina)...

**Comment by Valair** [comment]
> passaggio che mostra la mail ricevuta

Mmm è una issue ancora aperta lato portale e non si riceve alcuna mail...

> aspetterei quasi di vedere come inserire lo script

La procedura effettiva dipende dal linguaggio, dal framework, eventuali cms, temi. Se è così fuorviante preferisci venga tolta direttamente e lasciata solo la prima parte?

**Comment by danielaiozzo** [comment]
Sentiamoci un attimo domani Andrea! Così ti spiego meglio :)

Il giorno Mer 27 Nov 2019 18:41 Andrea Capelli <notifications@github.com>
ha scritto:

**Comment by pdavide** [comment]
@danielaiozzo questa è risolta?

**Comment by danielaiozzo** [comment]
si, se non ricordo male

Il giorno mar 11 feb 2020 alle ore 17:35 Davide Porrovecchio <
notifications@github.com> ha scritto:

**Comment by Valair** [comment]
@danielaiozzo @pdavide era stata risolta in quanto non era più necessario il video dell'onboarding.
Non ho feedback sui nuovi screencast, quindi immagino risolta.
